version: '3.7'

services:
  database_calistenic:
    image: postgres
    container_name: database_calistenic
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=calistenicnode
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: calistenicnode
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_calistenic
    depends_on:
      - database_calistenic

volumes:
  pgdata:
    driver: local